-- MySQL Script generated by MySQL Workbench
-- 05/01/16 23:28:54
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema attendDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema attendDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `attendDB` DEFAULT CHARACTER SET utf8 ;
USE `attendDB` ;

-- -----------------------------------------------------
-- Table `attendDB`.`T_USER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `attendDB`.`T_USER` (
  `user_idx` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_dir` CHAR(255) NOT NULL,
  `user_name` VARCHAR(45) NOT NULL,
  `user_attend` TINYINT(1) NOT NULL DEFAULT 0,
  `user_spec` INT UNSIGNED NOT NULL DEFAULT 0,
  `user_idnum` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`user_idx`),
  UNIQUE INDEX `user_idnum_UNIQUE` (`user_idnum` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
